### ISSUE TITLE
Final Commit Week 5

### ISSUE THREAD

**Issue by mceraso** [mceraso/TweetPath#2]
Hi Codepath, please review my app /cc @codepathreview

**Comment by minhchau273** [comment]
Hi Michael,

It looks like you still need to complete some required user stories for your submission to be complete. 
- [x] User can compose a new tweet by tapping on a compose button.

Your assignment needs to be updated within 24hrs in order for you to receive credit for this assignment.

Best,
Chau

**Comment by mceraso** [comment]
Hi @minhchau273,
Thank you for pointing this out. Are all required user stories complete now?
Best,
Michael

**Comment by minhchau273** [comment]
:+1: Nice work! We added this homework so that you'll have the experience building an app that's more similar in complexity to a production app. The optional account switching feature is interesting because you have to think about how TwitterClient is caching the access token to make sure it works correctly for multiple accounts.

### Some small comments:
- You should try using `delegate` to implement the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience.
- You should format the timestamp to make your app more friendly. :smile: 
- After tapping the `Post` button in `ComposeViewController`, your app should back to the timeline immediately instead of tapping Back button.
- It's a little bit hard for users to compose new tweet. They have to go to Profile screen first. :confused: 

We have a detailed [Project 5 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_5_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
